### ISSUE TITLE
Force Ansi Enabled

### ISSUE THREAD

**Issue by HarryCordewener** [yymqn/PastelEx#3]
There are situations where you don't care about the Console's support, or may know more about the environment than this code - for instance, because you may wish to display ANSI over other mediums.
Additionally, it looks like this may be hard-tied to only working on Windows.

Please give an override on Supported, so it can be set true - or allow a way in which Enabled is the Source of Truth.

**Comment by yymqn** [comment]
I changed the `Supported` property to have a public setter now. I'm working on a new project, which will replace PastelEx (currently closed source), so things might change by time.
